import clinical_medicine_randomized_controlled_trials_foundation_canonical_lane_mathlib.GateLemmas
import clinical_medicine_randomized_controlled_trials_foundation_canonical_lane_mathlib.FinalTheorem
